### ISSUE TITLE
Thoughts and weird bugs

### ISSUE THREAD

**Issue by Aisha-D** [eastgenomics/gene_annotation2bed#8]
- Check that the assembly & gtf use match; e.g same reference + both either do or do not contain chr (the assembly stats file doesnt have chr whereas the gff did in my case)
- Export pickle file to make it easier for user to rerun the script if needed, cause importing the gff and converting to a dataframe takes the longest. OR sense check the input files are correctly formatted then start to ingest the gff file. (i had a lot of errors with the input files but waiting a long time before an error was raised with the other input files)
- Sense check whether one of the rows has an empty annotation :upside_down_face: I was stuck with a weird error, so maybe raise error here for a blank annotation https://github.com/eastgenomics/gene_annotation2bed/blob/main/gene_annotation2bed.py#L588
- Add check that the correct assembly report is added and that it has the number of expected column https://github.com/eastgenomics/gene_annotation2bed/blob/main/gene_annotation2bed.py#L500

**Comment by Aisha-D** [comment]
- I added gff with chr, if there is presence of chr in gff, then select the last column of the assembly report. The output contained no chr-> https://github.com/eastgenomics/gene_annotation2bed/blob/main/gene_annotation2bed.py#L506
- I was using arg "-ref" which resulted in no error? not sure why an error was not thrown ( code is below)
- It also tried to create igv reports bed file when I did not request it and threw an error cause i did not provide a reference

```python3 gene_annotation2bed.py -ann ../uranus_gene2panel_v2.tsv -o test -ref ../GRCh38.no_alt_analysis_set_chr_mask21.fa.gz -f 5 -build hg38 --assembly_summary ../GCF_000001405.39_GRCh38.p13_assembly_report.txt -gff ../GCF_000001405.39_GRCh38.p13_genomic.gff```

**Comment by Aisha-D** [comment]
- Also the tabix didn't work, it errored out with a message saying the chromosome is not in order. I think the sort_result variable needs to be used when compressing? https://github.com/eastgenomics/gene_annotation2bed/blob/main/scripts/igv_report.py#L67

**Comment by RSWilson1** [comment]
Thanks for the bug report! I think I have fixed all the bugs mentioned and will add to PR. For the -ref problem seems to be how argparse handles cmd line arguments it autocomplete them by default.
